[build-dependencies]
build-target = "0.4.0"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
turborepo-lib = { workspace = true, default-features = false }

[dependencies.miette]
workspace = true

[dev-dependencies]
assert_cmd = { workspace = true }
camino = { workspace = true }
insta = { version = "1.40.0", features = ["json", "filters"] }
itertools = { workspace = true }
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
turbopath = { workspace = true }
which = { workspace = true }

[features]
default = ["rustls-tls", "turborepo-lib/daemon-package-discovery"]
native-tls = ["turborepo-lib/native-tls"]
pprof = ["turborepo-lib/pprof"]
rustls-tls = ["turborepo-lib/rustls-tls"]

[lints]
workspace = true

[package]
edition = "2024"
license = "MIT"
name = "turbo"
version = "0.1.0"
