[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tracing = { workspace = true }
turborepo-api-client = { workspace = true }
turborepo-vercel-api = { workspace = true }
uuid = { version = "1.5.0", features = ["v4"] }

[dependencies.futures]
workspace = true

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license = "MIT"
name = "turborepo-analytics"
version = "0.1.0"
