[dependencies]
const_format = "^0.2.0"
itertools = "^0.11.0"
nom = "^7.0.0"
pori = "=0.0.0"
thiserror = "^1.0.0"

[dependencies.miette]
default-features = false
optional = true
version = "7.5.0"

[dependencies.regex]
default-features = false
features = ["perf", "std", "unicode-case"]
version = "^1.9.0"

[dependencies.tardar]
optional = true
version = "^0.2.0"

[dependencies.walkdir]
optional = true
version = "^2.4.0"

[dev-dependencies]
build-fs-tree = "^0.6.0"
dunce = "^1.0.0"
path-slash = "0.2.1"
tempfile = "^3.8.0"

[features]
default = ["walk"]
miette = ["dep:miette", "dep:tardar"]
walk = ["dep:walkdir"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
categories = ["filesystem"]
description = "Opinionated and portable globs that can be matched against paths and directory trees."
edition = "2024"
keywords = ["glob", "pattern", "regex"]
license = "MIT"
name = "wax"
readme = "README.md"
repository = "https://github.com/olson-sean-k/wax"
version = "0.6.0"

[package.metadata]

[package.metadata.docs]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
