[dependencies]
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }

[dev-dependencies]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license = "MIT"
name = "turborepo-signals"
version = "0.1.0"
