[dependencies]
biome_deserialize = { workspace = true }
biome_diagnostics = { workspace = true }

[dependencies.serde]
workspace = true

[dependencies.serde_json]
workspace = true

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license-file = "LICENSE"
name = "turborepo-unescape"
version = "0.1.0"
