[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-server = "0.4.7"
futures-util = "0.3.28"
port_scanner = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turborepo-vercel-api = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license-file = "LICENSE"
name = "turborepo-vercel-api-mock"
version = "0.1.0"
