[package]
name = "turbopath"
version = "0.1.0"
license = "MIT"
edition = "2024"

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[features]
biome = [
  "dep:biome_deserialize",
  "dep:biome_deserialize_macros",
  "dep:biome_diagnostics",
  "dep:biome_json_parser",
  "dep:turborepo-unescape",
]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license-file = "LICENSE"
name = "turbopath"
version = "0.1.0"
