[dependencies]
biome_deserialize = { workspace = true, optional = true }
biome_deserialize_macros = { workspace = true, optional = true }
biome_diagnostics = { workspace = true, optional = true }
biome_json_parser = { workspace = true, optional = true }
camino = { workspace = true }
dunce = { workspace = true }
fs-err = "2.9.0"
miette = { workspace = true }
path-clean = "1.0.1"
serde = { workspace = true }
thiserror = { workspace = true }
turborepo-unescape = { workspace = true, optional = true }
wax = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[features]
biome = [
  "dep:biome_deserialize",
  "dep:biome_deserialize_macros",
  "dep:biome_diagnostics",
  "dep:biome_json_parser",
  "dep:turborepo-unescape",
]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license-file = "LICENSE"
name = "turbopath"
version = "0.1.0"
