[dependencies]
atty = { workspace = true }
console = { workspace = true }
reqwest = { workspace = true, features = ["json", "blocking"] }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
update-informer = { git = "https://github.com/nicholaslyang/update-informer.git", default-features = false, features = [
  "reqwest",
] }

[features]
native-tls = ["reqwest/native-tls", "update-informer/native-tls"]
rustls-tls = ["reqwest/rustls-tls", "update-informer/rustls-tls"]

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
description = "Minimal wrapper around update-informer to provide npm registry support and consistent UI"
edition = "2021"
license-file = "LICENSE"
name = "turbo-updater"
publish = false
version = "0.1.0"
