[package]
name = "turborepo-auth"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
axum-server = { workspace = true }
hostname = "0.3.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = "1.0.38"
turborepo-api-client = { workspace = true }
turborepo-dirs = { version = "0.1.0", path = "../turborepo-dirs" }
turborepo-vercel-api = { workspace = true }
turborepo-vercel-api-mock = { workspace = true }
url = { workspace = true }
webbrowser = { workspace = true }

[dependencies.async-trait]
workspace = true

[dependencies.axum]
workspace = true

[dependencies.chrono]
workspace = true

[dependencies.lazy_static]
workspace = true

[dependencies.reqwest]
workspace = true

[dependencies.tokio]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.turbopath]
workspace = true

[dependencies.turborepo-ui]
workspace = true

[dev-dependencies]
http = "1.1.0"
httpmock = { workspace = true }
port_scanner = { workspace = true }

[lib]
path = "Source/lib.rs"

[lints]
workspace = true

[package]
edition = "2024"
license-file = "LICENSE"
name = "turborepo-auth"
version = "0.1.0"
